apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: bluevpc-connections
  namespace: monitoring
  labels:
    prometheus: bluevpc-connections
    release: prom
spec:
  scheme: HTTP
  metricsPath: /metrics
  staticConfigs:
    - labels:
        job: bluevpc-connections
      targets:
        - trol.geracorp.org:9318
