apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: low-disk-alerting
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  groups:
  - name: low-disk
    rules:
      - alert: "HostOutOfDiskSpace"
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          description: "Disk is almost full (< 10% left)"
          value: "{{ $value }}"
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 2m
        labels:
          severity: critical
